export const bestsellersFromBackend = [
  {
    order_id: '1',
    title: 'Patterned Bandeau Dress',
    image: '/imgDelete/bestseller-1.jpg',
    colors: ['black', 'blue', 'white'],
    price: 74.99,
    size: 'XL',
    color: '',
    count: 1,
  },
  {
    order_id: '2',
    title: 'Twill Trench Coat',
    image: '/imgDelete/bestseller-2.jpg',
    colors: ['brown', 'white'],
    price: 59.99,
    size: 'XL',
    color: '',
    count: 1,
  },
  {
    order_id: '3',
    title: 'Chunky Sneakers',
    image: '/imgDelete/bestseller-3.jpg',
    colors: ['grey', 'white'],
    price: 67.99,
    size: 'XL',
    color: '',
    count: 1,
  },
  {
    order_id: '4',
    title: 'Regular Fit Shirt',
    image: '/imgDelete/bestseller-4.jpg',
    colors: ['beige', 'white'],
    price: 23.99,
    size: 'XL',
    color: '',
    count: 1,
  },
];

export const looksFromBackend = [
  {
    lookName: 'firstLook',
    lookImg: '/imgDelete/firstLook.jpg',
    items: [
      {
        order_id: '1',
        title: 'Oversized Button-front Grey Jacket',
        image: '/imgDelete/firstLook-item1.jpg',
        colors: ['grey'],
        price: 39.99,
        size: 'XL',
        color: '',
        count: 1,
      },
      {
        order_id: '2',
        title: 'Straight High Jeans',
        image: '/imgDelete/firstLook-item2.jpg',
        colors: ['grey'],
        price: 29.99,
        size: 'XL',
        color: '',
        count: 1,
      },
      {
        order_id: '3',
        title: 'Ribbed Tank Top',
        image: '/imgDelete/firstLook-item3.jpg',
        colors: ['beige'],
        price: 12.99,
        size: 'XL',
        color: '',
        count: 1,
      },
    ],
  },
  {
    lookName: 'secondLook',
    lookImg: '/imgDelete/secondLook.jpg',
    items: [
      {
        order_id: '1',
        title: 'Oversized Button-front Violet Jacket',
        image: '/imgDelete/secondLook-item1.jpg',
        colors: ['violet'],
        price: 29.99,
        size: 'XL',
        color: '',
        count: 1,
      },
      {
        order_id: '2',
        title: 'Straight High Violet Jeans',
        image: '/imgDelete/secondLook-item2.jpg',
        colors: ['violet'],
        price: 19.99,
        size: 'XL',
        color: '',
        count: 1,
      },
      {
        order_id: '3',
        title: 'Ribbed Tank Violet Top',
        image: '/imgDelete/secondLook-item3.jpg',
        colors: ['violet'],
        price: 42.99,
        size: 'XL',
        color: '',
        count: 1,
      },
    ],
  },
];
