export enum Routes {
  ROOT = '/',
  SHOP = '/shop',
  SHOP_WOMEN = '/shop?category=women',
  SHOP_MEN = '/shop?category=men',
  SHOP_KIDS = '/shop?category=kids',
  SHOP_ACCESSORIES = '/shop?category=accessories',
  SALE = '/sale',
  WISHLIST = '/wishlist',
  PROFILE = '/profile',
  CART = '/cart',
  CUSTOMER_SERVICE = '/customer-service',
  TRACK_ORDER = '/track-order',
  LEGAL_PRIVACY = '/legal_privacy',
  CONTACT = '/contact',
  FAQ = '/faq',
}
