export enum Routes {
  ROOT = '/',
  SHOP = '/shop',
  SHOP_WOMEN = '/shop?category=women',
  SHOP_MEN = '/shop?category=men',
  SHOP_KIDS = '/shop?category=kids',
  SHOP_ACCESSORIES = '/shop?category=accessories',
  
  SALE = '/sale',
  WISHLIST = '/wishlist',
  CUSTOMER_SERVICE = '/customer-service',
  TRACK_ORDER = '/track-order',
  LEGAL_PRIVACY = '/legal-privacy',
  SHIPPING_INFO = '/shipping-info',
  CONTACT = '/contact',
  REFUND = '/refund',
  ACCOUNT = '/account',
  LOCATIONS = '/location',
  CAREER = '/career',
  GIFT_CARDS = '/gift-cards',
  ABOUT_US = '/about-us',
  CATEGORIES = '/categories',
  CART = '/cart',
  CHECKOUT = '/cart/checkout',
  //Profile Links
  ORDERS = '/orders',
  SETTINGS = '/settings',
  REWARDS = '/rewards',
  TERMS_OF_USE = '/terms',
  PRIVACY_POLICY = '/privacy-policy',
  // Auth Links
  SIGN_UP = '/sign-up',
  SIGN_IN = '/sign-in',
  FORGOT_PASSWORD = '/password/forgot',
  RESET_PASSWORD = '/password/reset',
}
